# Generated by Django 3.2.4 on 2021-06-23 20:19

import aptusadmin.utils
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aptusadmin', '0003_auto_20210623_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=64, verbose_name='Libellé')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Enfants', to='e_commerce.categorie', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aptusadmin.customuser')),
                ('tel', models.CharField(blank=True, default='', max_length=25, verbose_name='Téléphone')),
                ('genre', models.CharField(blank=True, choices=[('', ''), ('F', 'Femme'), ('H', 'Homme')], default='', max_length=1, verbose_name='Genre')),
                ('adresse', models.CharField(blank=True, default='', max_length=128, verbose_name='Adresse')),
                ('adresse_livraison', models.CharField(blank=True, default='', max_length=128, verbose_name='Adresse de livraison')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'default_permissions': (),
            },
            bases=('aptusadmin.customuser',),
            managers=[
                ('myapps_manager', aptusadmin.utils.CustomUserManager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now=True, verbose_name='Date commande')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20, verbose_name='FullName')),
                ('email', models.EmailField(max_length=20, verbose_name='Email')),
                ('subject', models.TextField(max_length=30, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_produit', models.CharField(max_length=64, unique=True, verbose_name='Référence')),
                ('nom_produit', models.CharField(max_length=64, verbose_name='Nom')),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix')),
                ('description_produit', models.TextField(verbose_name='description')),
                ('descriptif', models.TextField(blank=True, default='', verbose_name='Descriptif')),
                ('qte_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité en stock')),
                ('categorie', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProduitPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField(blank=True, default=1, verbose_name='Quantité')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.panier', verbose_name='Panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Produit de panier',
                'verbose_name_plural': 'Produits de panier',
                'unique_together': {('panier', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='ProduitCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField(blank=True, default=1, verbose_name='Quantité')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.commande', verbose_name='Commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Produit de commande',
                'verbose_name_plural': 'Produits de commande',
                'unique_together': {('commande', 'produit')},
            },
        ),
        migrations.AddField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(blank=True, through='e_commerce.ProduitPanier', to='e_commerce.Produit', verbose_name='Produits de panier'),
        ),
        migrations.CreateModel(
            name='NoteDeRecommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.client', verbose_name='Client')),
                ('produit_commente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.produit', verbose_name='Produit commenté')),
            ],
            options={
                'verbose_name': 'Note de recommandation',
                'verbose_name_plural': 'Notes de recommandation',
                'permissions': (('add_note_recommandation', 'Ajouter une note de recommandation'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FichierProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_jointe', models.FileField(upload_to='produits/pieces_jointes')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce.produit')),
            ],
            options={
                'verbose_name': 'Fichier produit',
                'verbose_name_plural': 'Fichiers produit',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='e_commerce.ProduitCommande', to='e_commerce.Produit', verbose_name='Produits'),
        ),
    ]
