# Generated by Django 3.2.4 on 2021-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cross_sales',
            field=models.ManyToManyField(related_name='_e_commerce_produit_cross_sales_+', to='e_commerce.Produit', verbose_name='Cross-salses'),
        ),
        migrations.AddField(
            model_name='produit',
            name='upsales',
            field=models.ManyToManyField(related_name='_e_commerce_produit_upsales_+', to='e_commerce.Produit', verbose_name='Upsalses'),
        ),
    ]
