# Generated by Django 3.2.4 on 2021-06-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0002_auto_20210626_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notederecommandation',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': (('add_note_recommandation', 'Ajouter une note de recommandation'),), 'verbose_name': 'Note de recommandation', 'verbose_name_plural': 'Notes de recommandation'},
        ),
        migrations.AlterField(
            model_name='produit',
            name='cross_sales',
            field=models.ManyToManyField(blank=True, help_text='Cross-selling invites customers to buy related or complementary items.', related_name='_e_commerce_produit_cross_sales_+', to='e_commerce.Produit', verbose_name='Cross-salses'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='upsales',
            field=models.ManyToManyField(blank=True, help_text='Upselling is the practice of encouraging customers to purchase a comparable higher-end product than the one in question', related_name='_e_commerce_produit_upsales_+', to='e_commerce.Produit', verbose_name='Upsalses'),
        ),
    ]
