# Generated by Django 3.2.4 on 2021-06-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0003_auto_20210627_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
