# Generated by Django 3.2.4 on 2021-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0004_produit_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
