# Generated by Django 3.2.4 on 2021-06-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0006_auto_20210627_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_ajout',
            field=models.DateField(auto_now=True),
        ),
    ]
