# Generated by Django 3.2.4 on 2021-06-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0007_produit_date_ajout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='cross_sales',
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_ajout',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CrossSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='e_commerce.produit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='e_commerce.produit')),
            ],
        ),
    ]
