# Generated by Django 3.2.4 on 2021-06-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0008_auto_20210628_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cross_sales',
            field=models.ManyToManyField(blank=True, help_text='Cross-selling invites customers to buy related or complementary items.', related_name='_e_commerce_produit_cross_sales_+', through='e_commerce.CrossSell', to='e_commerce.Produit', verbose_name='Cross-salses'),
        ),
    ]
