# Generated by Django 3.2.4 on 2021-06-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0009_produit_cross_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosssell',
            name='cross_sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crosssell_set', to='e_commerce.produit'),
        ),
    ]
