# Generated by Django 3.2.4 on 2021-06-28 14:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0010_alter_crosssell_cross_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description_produit',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
    ]
