# Generated by Django 3.2.4 on 2021-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0011_alter_produit_description_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slider')),
            ],
        ),
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, upload_to='produits/categories/images'),
        ),
    ]
