# Generated by Django 3.2.4 on 2021-06-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0013_auto_20210628_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site settings', 'verbose_name_plural': 'Site settings'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nom_entreprise',
            field=models.ImageField(blank=True, upload_to='images/logos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='horaires_travail',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tel_contact',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
