# Generated by Django 3.2.4 on 2021-06-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0015_auto_20210629_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='payee',
            field=models.BooleanField(default=False, verbose_name='Payée'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateField(auto_now_add=True, verbose_name='Date commande'),
        ),
    ]
