# Generated by Django 3.2.4 on 2021-06-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0016_auto_20210629_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(upload_to='produits/categories/images'),
        ),
    ]
