# Generated by Django 3.2.4 on 2021-06-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0017_alter_categorie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(default=1, upload_to='images/logos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='prix_livraison_standard',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
