# Generated by Django 3.2.4 on 2021-06-30 16:53

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0018_auto_20210629_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Paramètres du site', 'verbose_name_plural': 'Paramètres du site'},
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_livraison',
            field=models.CharField(choices=[('LS', 'Livraison Standard'), ('EP', 'Envoie Postal Economique')], default='LS', max_length=2, verbose_name='Mode de livraison'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Ce champ est utilisé pour trier les produits par popularité.', verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='payee',
            field=models.BooleanField(default=False, verbose_name='Commande Payée'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='cross_sales',
            field=models.ManyToManyField(blank=True, help_text='Cross-selling est une pratique qui invite les clients à acheter des articles liés ou complémentaires à des produits dans leurs paniers.<br/>', related_name='_e_commerce_produit_cross_sales_+', through='e_commerce.CrossSell', to='e_commerce.Produit', verbose_name='Cross-sells'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='upsales',
            field=models.ManyToManyField(help_text='Upselling est une pratique qui consiste à encourager les clients à acheter un produit haut de gamme comparable à celui en question.<br/>', related_name='_e_commerce_produit_upsales_+', to='e_commerce.Produit', verbose_name='Upsells'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Ce champ est utilisé pour trier les produits par popularité.', verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us_text',
            field=ckeditor.fields.RichTextField(verbose_name='Texte de la page About us'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='adresse',
            field=models.CharField(max_length=50, verbose_name="Adresse de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_envoie_contact',
            field=models.EmailField(default='exemple@gmail.com', max_length=254, verbose_name="Adresse mail d'envoie des message de contact"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_reception_contact',
            field=models.EmailField(default='exemple@gmail.com', max_length=254, verbose_name='Adresse mail de réception des messages de contact'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='horaires_travail',
            field=models.CharField(max_length=45, verbose_name='Horaires de travail'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lien_facebook',
            field=models.CharField(default='https://www.facebook.com/', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lien_instagram',
            field=models.CharField(default='https://www.instagram.com/', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='lien_twitter',
            field=models.CharField(default='https://www.twitter.com/', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(upload_to='images/logos', verbose_name='Logo du header'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='nom_entreprise',
            field=models.CharField(max_length=50, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='password_envoie_contact',
            field=models.CharField(max_length=20, verbose_name="Mot de passe de l'adresse mail d'envoie"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='prix_livraison_standard',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_primary_color',
            field=colorfield.fields.ColorField(default='#3abbc2', max_length=18, verbose_name='Couleur primaire du site'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tel_contact',
            field=models.CharField(default='+212-xxxxxxxxx', max_length=20, verbose_name='Téléphone de contact'),
        ),
    ]
