# Generated by Django 3.2.4 on 2021-06-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0019_auto_20210630_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_sec',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Code de sécurité de la carte de paiement'),
        ),
        migrations.AddField(
            model_name='client',
            name='num_cart',
            field=models.CharField(blank=True, default='', max_length=19, verbose_name='Numero de la carte de paiement'),
        ),
    ]
