# Generated by Django 3.2.4 on 2021-06-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0020_auto_20210630_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration de la carte de paiement"),
        ),
    ]
