# Generated by Django 3.2.4 on 2021-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0022_auto_20210701_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('C', 'Par carte bancaire'), ('P', 'Paypal'), ('A', 'A la livraison')], default='C', max_length=1, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, upload_to='produits/categories/images'),
        ),
    ]
