# Generated by Django 3.2.4 on 2021-07-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0023_auto_20210701_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='Paypal_client_id',
            field=models.CharField(default='', help_text='Saisir le client ID du compte Paypal à partir duquel vous souhaitez recevoir les paiements des clients.', max_length=100, verbose_name='Client ID du compte Paypal'),
            preserve_default=False,
        ),
    ]
