# Generated by Django 3.2.4 on 2021-07-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0025_auto_20210702_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Sommaire de Produit',
                'verbose_name_plural': 'Sommaire des Produits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('e_commerce.produit',),
        ),
        migrations.AlterModelOptions(
            name='notederecommandation',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': (('add_note_recommandation', 'Ajouter une note de recommandation'),), 'verbose_name': 'Note de recommandation', 'verbose_name_plural': 'Notes de recommandation'},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Ce champ est utilisé pour trier les catégories par popularité.', verbose_name='Nombre de vues'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(max_length=40, verbose_name='FullName'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.TextField(max_length=40, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_produit',
            field=models.DecimalField(decimal_places=2, help_text='Prix du produit en Dhs.', max_digits=8, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='reference_produit',
            field=models.CharField(help_text='La référence du produit doit être unique!', max_length=64, unique=True, verbose_name='Référence'),
        ),
    ]
