# Generated by Django 3.2.4 on 2021-07-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0026_auto_20210704_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduitSummary',
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date commande'),
        ),
    ]
