# Generated by Django 3.2.4 on 2021-07-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0028_alter_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='genre',
            field=models.CharField(blank=True, choices=[('', ''), ('F', 'Femme'), ('H', 'Homme')], default='H', max_length=1, verbose_name='Genre'),
        ),
    ]
