# Generated by Django 3.2.4 on 2021-07-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0029_alter_client_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banque',
            field=models.CharField(default='', help_text='Le nom de la banque pour le mode de paiement du virement bancaire.', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='num_rib',
            field=models.CharField(default='', max_length=100, verbose_name='Numéro RIB'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('C', 'Par carte bancaire'), ('P', 'Paypal'), ('A', 'A la livraison'), ('V', 'Virement bancaire')], default='C', max_length=1, verbose_name='Mode de paiement'),
        ),
    ]
