# Generated by Django 3.2.4 on 2021-07-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0030_auto_20210705_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='modes_paiement',
            field=models.CharField(choices=[('C', 'Par carte bancaire'), ('P', 'Paypal'), ('A', 'A la livraison'), ('V', 'Virement bancaire')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='num_rib',
            field=models.CharField(help_text='Le numéro RIB de du compte bancaire pour recevoir les virements bancaires.', max_length=100, verbose_name='Numéro RIB'),
        ),
    ]
