# Generated by Django 3.2.4 on 2021-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0031_auto_20210705_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='modes_paiement',
            field=models.CharField(choices=[('C', 'Par carte bancaire'), ('P', 'Paypal'), ('A', 'A la livraison'), ('V', 'Virement bancaire')], default='C', max_length=1, verbose_name='Modes de paiement'),
        ),
    ]
