# Generated by Django 3.2.4 on 2021-07-06 08:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0032_alter_sitesettings_modes_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='modes_paiement',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Par carte bancaire'), ('P', 'Paypal'), ('A', 'A la livraison'), ('V', 'Virement bancaire')], max_length=1, verbose_name='Modes de paiement'),
        ),
    ]
