# Generated by Django 3.2.4 on 2021-07-06 08:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0033_alter_sitesettings_modes_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nouveau',
            field=models.BooleanField(default=False, help_text="Marquer le produit comme 'nouveau', pour l'afficher dans la liste des nouveautés dans la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='modes_paiement',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('C', 'Par carte bancaire'), ('P', 'Paypal'), ('A', 'A la livraison'), ('V', 'Virement bancaire')], max_length=7, verbose_name='Modes de paiement'),
        ),
    ]
