# Generated by Django 3.2.4 on 2021-07-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0034_auto_20210706_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'default_permissions': (), 'ordering': ['-id'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='conditions_utilisation',
            field=models.FileField(default='', upload_to='fichiers/conditions_utilisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='banque',
            field=models.CharField(blank=True, default='', help_text='Le nom de la banque pour le mode de paiement du virement bancaire.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='num_rib',
            field=models.CharField(blank=True, default='', help_text='Le numéro RIB de du compte bancaire pour recevoir les virements bancaires.', max_length=100, verbose_name='Numéro RIB'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='paypal_client_id',
            field=models.CharField(blank=True, default='', help_text='Saisir le client ID du compte Paypal à partir duquel vous souhaitez recevoir les paiements des clients.', max_length=120, verbose_name='Client ID du compte Paypal'),
        ),
    ]
