# Generated by Django 3.2.4 on 2021-09-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0037_produit_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='thumbnail',
        ),
    ]
