# Generated by Django 3.2.4 on 2021-09-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0038_remove_produit_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/products_thumb/'),
        ),
    ]
