# Generated by Django 3.2.4 on 2021-09-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0039_produit_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='absolute_url',
            field=models.TextField(default='http://localhost:8000/produits/22', verbose_name='Absolute_url'),
        ),
    ]
