# Generated by Django 3.2.4 on 2021-09-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce', '0040_produit_absolute_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='absolute_url',
        ),
    ]
