from django.urls import path, include

from e_commerce import api_views
from e_commerce import views

urlpatterns = [
    path('api/v1/', include('djoser.urls')),
    path('api/v1/', include('djoser.urls.authtoken')),
    path("custom_users/",
         api_views.CustomUserList.as_view(),
         name="custom_users_list"),
    path("custom_users/<int:pk>/",
         api_views.CustomUserDetail.as_view(),
         name="custom_users_detail"),
    path("clients/",
         api_views.ClientCreateList.as_view(),
         name="client_create_list"),
    path("clients/<int:pk>/",
         api_views.ClientDetailUpdateDelete.as_view(),
         name="client_detail_update_delete"),
    # Fecth all categorie
    path("categories/",
         api_views.CategoriesList.as_view(),
         name="categories_list"),
    # Fecth categorie by id with enfants categories
    path("categories/<int:pk>/",
         api_views.CategorieDetail.as_view(),
         name="categorie_detail"),
    # Fecth categorie by id with parent categories
    path("categories2/<int:pk>/",
         api_views.CategorieDetail2.as_view(),
         name="categorie_detail2"),
    # Fecth all produit
    path("produits/", api_views.ProduitsList.as_view(), name="produits_list"),
    path("produits/<int:pk>/",
         api_views.ProduitDetail.as_view(),
         name="produit_detail"),
    # Fecth all produits by categorie pk:id's given
    path("produits/categorie/<int:pk>/",
         api_views.ProduitsCategorie.as_view(),
         name="produits_categorie"),
    path("produits/ajouter/",
         api_views.ProduitAjouter.as_view(),
         name="produits_ajouter"),
    path("fichiers_produit/ajouter/",
         api_views.FichierProduitAjouter.as_view(),
         name="fichiers_produit_ajouter"),
    path("fichiers_produit/",
         api_views.FichiersProduitList.as_view(),
         name="fichiers_produit_list"),
    path("fichiers_produit/<int:pk>/",
         api_views.FichierProduitDetail.as_view(),
         name="fichier_produit_detail"),
    path("panier/", api_views.NewPanier.as_view(), name="panier_new"),
    path("panier/<int:pk>/",
         api_views.PanierDetail.as_view(),
         name="panier_detail"),
    path("panier/ajouter/",
         api_views.AjouterAuPanier.as_view(),
         name="ajouter_au_panier"),
    path("panier/supprimer/<int:pk>/",
         api_views.SupprimerDuPanier.as_view(),
         name="supprimer_du_panier"),
    path("produit_panier/<int:pk>/",
         api_views.PorduitPanierDetail.as_view(),
         name="produit_panier_detail"),
    path("produit_panier/modifier/<int:pk>/",
         api_views.PorduitPanierModifier.as_view(),
         name="produit_panier_modifier"),
    path("commandes/", api_views.NewCommade.as_view(), name="new_commande"),
    path("commandes/produits_commande/",
         api_views.AjouterProduitCommande.as_view(),
         name="ajouter_commande"),
    path("commandes/client/<int:pk>/",
         api_views.CommandesClient.as_view(),
         name="commandes_client"),
    path("note/ajouter/", api_views.AjouterNote.as_view(),
         name="ajouter_note"),
    path("notes/", api_views.NotesList.as_view(), name="notes_list"),
    path("notes/produit/<int:pk>/",
         api_views.NotesProduit.as_view(),
         name="notes_produit"),
    path("contactUs/", api_views.ContactUs.as_view(), name="contact_us"),
    path("images_slider/",
         api_views.ImageSliderListe.as_view(),
         name="images_slider"),
    path("site_settings/",
         api_views.SiteSettingsDetail.as_view(),
         name="site_settings"),
]

# Set by Yattara
urlpatterns += [
    path('produits/search/', api_views.search),
    path('signup/', api_views.CreateClientView.as_view()),
    path('api-auth/', include('dj_rest_auth.registration.urls')), # new
    path('api-auth/', include('dj_rest_auth.urls')), # new
]
