# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-18 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('aptusadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
            ],
            options={
                'verbose_name_plural': "Journal d'activités",
                'ordering': ['-id'],
                'proxy': True,
                'default_permissions': ('viewlist',),
                'indexes': [],
            },
            bases=('admin.logentry',),
        ),
    ]
