# Generated by Django 3.2.4 on 2021-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptusadmin', '0003_auto_20210623_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='must_change_pwd',
            field=models.BooleanField(default=False),
        ),
    ]
