# Generated by Django 3.2.4 on 2021-07-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptusadmin', '0004_alter_customuser_must_change_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
